ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: app.lookstar.com.cn
      paths:
        - path: /central-admin
          pathType: ImplementationSpecific

  tls:
    - secretName: lookstar.com.cn
      hosts:
        - lookstar.com.cn
