ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: beta-app.lookstar.com.cn
      paths:
        - backend:
            serviceName: lookstar-central-beta
            servicePort: 80
          path: /central
  tls:
    - secretName: lookstar.com.cn
      hosts:
        - lookstar.com.cn
