export default {
  API_URL: '',
  OSS_URL: '/backend/system/resource/oss-upload-url',
  ACCESS_TOKEN_NAME: 'blue-dot-project-token',
  RSA_PUBLIC_KEY: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8ZuA7eHwo7YeJFy7+plED6V89N6QoRHVLX+cMAEzt4f6ZOM59yaA89HM03luNTlQRlFr+PNZKwMmfZU9lNsx
CQQDkZztBnfr3f4pwJmt0Dlw4Dr+tY0091dMI9J+5lC8JyIGq+yGAOfFUJZWp83r
s7bLorS9/6i4yI10G6LlSEwI6I7J6gBAKEHfGsUEdnJGhShKVBwEMQcXanz+w3up
aVY+OgIIuMWmXwPK2GQ3kYDJ4AEtoFafalgSAv5mnyvcMuWVsQCHzHaYawO8loao
tpZ6jUPKFJMqnM/F7ykr4sWzrleT8mPVx/2CRLSrvMhUmwGzIEXMzkVylQt3Luwu
ZQIDAQAB
-----END PUBLIC KEY-----`,
};
